-- 코드를 입력하세요
# ONLINE_SALE_ID 상품 판매 ID
# USER_ID  회원 ID
# PRODUCT_ID 상품 ID
# SALES_AMOUNT 판매량
# SALES_DATE 판매일
SELECT USER_ID, PRODUCT_ID
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID
HAVING COUNT(*) > 1
ORDER BY USER_ID ASC, PRODUCT_ID DESC