SELECT I.FOOD_TYPE, REST_ID, REST_NAME, I.FAVORITES
FROM REST_INFO I
JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES 
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) V
ON I.FAVORITES = V.FAVORITES AND I.FOOD_TYPE = V.FOOD_TYPE
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC